name: aplikasi_tutor_pribadi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.0  # Perhatikan bahwa mysql1 diletakkan di bawah flutter dengan indentasi yang benar
  sqflite: ^2.0.0+4
  path: ^1.9.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
